### ISSUE TITLE
Problème de sécurité !

### ISSUE THREAD

**Issue by bsoufflet** [anthomir/Speleograph#1]
Tout le monde peut voir ce fichier avec des mots de passe et des informations personnelles.
Il faut supprimer ce fichier du repo et changer les mots de passes et clés qui ont maintenant fuitées...

https://github.com/anthomir/Speleograph/blob/main/.env

**Comment by bsoufflet** [comment]
![image](https://github.com/anthomir/Speleograph/assets/985903/23d4ed1f-380f-4ada-88c4-00fa770de5d8)

**Comment by rtroncy** [comment]
Thanks for alerting. This is indeed a very bad practice. The app deployed in production does not use these credentials. This file will indeed be removed.
